"""add cascade delete behavior to foreign keys

Revision ID: 658c4b61b5e1
Revises: 609bf363c1fd
Create Date: 2026-09-18 14:21:59.686154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658c4b61b5e1'
down_revision: Union[str, Sequence[str], None] = '609bf363c1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('accuracy_claims_reviewer_id_fkey'), 'accuracy_claims', type_='foreignkey')
    op.drop_constraint(op.f('accuracy_claims_video_id_fkey'), 'accuracy_claims', type_='foreignkey')
    op.drop_constraint(op.f('accuracy_claims_study_id_fkey'), 'accuracy_claims', type_='foreignkey')
    op.create_foreign_key('accuracy_claims_video_id_fkey', 'accuracy_claims', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('accuracy_claims_study_id_fkey', 'accuracy_claims', 'studies', ['study_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('accuracy_claims_reviewer_id_fkey', 'accuracy_claims', 'reviewers', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('accuracy_review_status_reviewer_id_fkey'), 'accuracy_review_status', type_='foreignkey')
    op.drop_constraint(op.f('accuracy_review_status_video_id_fkey'), 'accuracy_review_status', type_='foreignkey')
    op.drop_constraint(op.f('accuracy_review_status_study_id_fkey'), 'accuracy_review_status', type_='foreignkey')
    op.create_foreign_key('accuracy_review_status_reviewer_id_fkey', 'accuracy_review_status', 'reviewers', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('accuracy_review_status_study_id_fkey', 'accuracy_review_status', 'studies', ['study_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('accuracy_review_status_video_id_fkey', 'accuracy_review_status', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('audit_log_reviewer_id_fkey'), 'audit_log', type_='foreignkey')
    op.drop_constraint(op.f('audit_log_study_id_fkey'), 'audit_log', type_='foreignkey')
    op.create_foreign_key('audit_log_study_id_fkey', 'audit_log', 'studies', ['study_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('audit_log_reviewer_id_fkey', 'audit_log', 'reviewers', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('double_coding_samples_study_id_fkey'), 'double_coding_samples', type_='foreignkey')
    op.drop_constraint(op.f('double_coding_samples_video_id_fkey'), 'double_coding_samples', type_='foreignkey')
    op.create_foreign_key('double_coding_samples_video_id_fkey', 'double_coding_samples', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('double_coding_samples_study_id_fkey', 'double_coding_samples', 'studies', ['study_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('full_search_runs_study_id_fkey'), 'full_search_runs', type_='foreignkey')
    op.drop_constraint(op.f('full_search_runs_approval_id_fkey'), 'full_search_runs', type_='foreignkey')
    op.create_foreign_key('full_search_runs_study_id_fkey', 'full_search_runs', 'studies', ['study_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('full_search_runs_approval_id_fkey', 'full_search_runs', 'search_strategy_approvals', ['approval_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('information_domain_codes_video_coding_id_fkey'), 'information_domain_codes', type_='foreignkey')
    op.create_foreign_key('information_domain_codes_video_coding_id_fkey', 'information_domain_codes', 'video_coding', ['video_coding_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('older_adult_need_codes_video_coding_id_fkey'), 'older_adult_need_codes', type_='foreignkey')
    op.create_foreign_key('older_adult_need_codes_video_coding_id_fkey', 'older_adult_need_codes', 'video_coding', ['video_coding_id'], ['id'], ondelete='CASCADE')
    op.alter_column('pilot_search_results', 'query_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('pilot_search_results_reviewer_id_fkey'), 'pilot_search_results', type_='foreignkey')
    op.drop_constraint(op.f('pilot_search_results_query_id_fkey'), 'pilot_search_results', type_='foreignkey')
    op.drop_constraint(op.f('pilot_search_results_pilot_search_run_id_fkey'), 'pilot_search_results', type_='foreignkey')
    op.create_foreign_key('pilot_search_results_reviewer_id_fkey', 'pilot_search_results', 'reviewers', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('pilot_search_results_query_id_fkey', 'pilot_search_results', 'search_queries', ['query_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('pilot_search_results_pilot_search_run_id_fkey', 'pilot_search_results', 'pilot_search_runs', ['pilot_search_run_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('pilot_search_runs_reviewer_id_fkey'), 'pilot_search_runs', type_='foreignkey')
    op.drop_constraint(op.f('pilot_search_runs_study_id_fkey'), 'pilot_search_runs', type_='foreignkey')
    op.create_foreign_key('pilot_search_runs_study_id_fkey', 'pilot_search_runs', 'studies', ['study_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('pilot_search_runs_reviewer_id_fkey', 'pilot_search_runs', 'reviewers', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('presentation_codes_video_coding_id_fkey'), 'presentation_codes', type_='foreignkey')
    op.create_foreign_key('presentation_codes_video_coding_id_fkey', 'presentation_codes', 'video_coding', ['video_coding_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('screening_decisions_reviewer_id_fkey'), 'screening_decisions', type_='foreignkey')
    op.drop_constraint(op.f('screening_decisions_video_id_fkey'), 'screening_decisions', type_='foreignkey')
    op.drop_constraint(op.f('screening_decisions_study_id_fkey'), 'screening_decisions', type_='foreignkey')
    op.create_foreign_key('screening_decisions_study_id_fkey', 'screening_decisions', 'studies', ['study_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('screening_decisions_reviewer_id_fkey', 'screening_decisions', 'reviewers', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('screening_decisions_video_id_fkey', 'screening_decisions', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('search_queries_study_id_fkey'), 'search_queries', type_='foreignkey')
    op.create_foreign_key('search_queries_study_id_fkey', 'search_queries', 'studies', ['study_id'], ['id'], ondelete='CASCADE')
    op.alter_column('search_results_raw', 'query_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('search_results_raw_full_search_run_id_fkey'), 'search_results_raw', type_='foreignkey')
    op.drop_constraint(op.f('search_results_raw_query_id_fkey'), 'search_results_raw', type_='foreignkey')
    op.create_foreign_key('search_results_raw_full_search_run_id_fkey', 'search_results_raw', 'full_search_runs', ['full_search_run_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('search_results_raw_query_id_fkey', 'search_results_raw', 'search_queries', ['query_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('search_strategy_approvals_study_id_fkey'), 'search_strategy_approvals', type_='foreignkey')
    op.drop_constraint(op.f('search_strategy_approvals_reviewer_id_fkey'), 'search_strategy_approvals', type_='foreignkey')
    op.create_foreign_key('search_strategy_approvals_reviewer_id_fkey', 'search_strategy_approvals', 'reviewers', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('search_strategy_approvals_study_id_fkey', 'search_strategy_approvals', 'studies', ['study_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('video_coding_reviewer_id_fkey'), 'video_coding', type_='foreignkey')
    op.drop_constraint(op.f('video_coding_study_id_fkey'), 'video_coding', type_='foreignkey')
    op.drop_constraint(op.f('video_coding_video_id_fkey'), 'video_coding', type_='foreignkey')
    op.create_foreign_key('video_coding_study_id_fkey', 'video_coding', 'studies', ['study_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('video_coding_video_id_fkey', 'video_coding', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('video_coding_reviewer_id_fkey', 'video_coding', 'reviewers', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('videos_study_id_fkey'), 'videos', type_='foreignkey')
    op.create_foreign_key('videos_study_id_fkey', 'videos', 'studies', ['study_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('videos_study_id_fkey'), 'videos', type_='foreignkey')
    op.create_foreign_key(op.f('videos_study_id_fkey'), 'videos', 'studies', ['study_id'], ['id'])
    op.drop_constraint(op.f('video_coding_video_id_fkey'), 'video_coding', type_='foreignkey')
    op.drop_constraint(op.f('video_coding_study_id_fkey'), 'video_coding', type_='foreignkey')
    op.drop_constraint(op.f('video_coding_reviewer_id_fkey'), 'video_coding', type_='foreignkey')
    op.create_foreign_key(op.f('video_coding_video_id_fkey'), 'video_coding', 'videos', ['video_id'], ['id'])
    op.create_foreign_key(op.f('video_coding_study_id_fkey'), 'video_coding', 'studies', ['study_id'], ['id'])
    op.create_foreign_key(op.f('video_coding_reviewer_id_fkey'), 'video_coding', 'reviewers', ['reviewer_id'], ['id'])
    op.drop_constraint(op.f('search_strategy_approvals_reviewer_id_fkey'), 'search_strategy_approvals', type_='foreignkey')
    op.drop_constraint(op.f('search_strategy_approvals_study_id_fkey'), 'search_strategy_approvals', type_='foreignkey')
    op.create_foreign_key(op.f('search_strategy_approvals_reviewer_id_fkey'), 'search_strategy_approvals', 'reviewers', ['reviewer_id'], ['id'])
    op.create_foreign_key(op.f('search_strategy_approvals_study_id_fkey'), 'search_strategy_approvals', 'studies', ['study_id'], ['id'])
    op.drop_constraint(op.f('search_results_raw_query_id_fkey'), 'search_results_raw', type_='foreignkey')
    op.drop_constraint(op.f('search_results_raw_full_search_run_id_fkey'), 'search_results_raw', type_='foreignkey')
    op.create_foreign_key(op.f('search_results_raw_query_id_fkey'), 'search_results_raw', 'search_queries', ['query_id'], ['id'])
    op.create_foreign_key(op.f('search_results_raw_full_search_run_id_fkey'), 'search_results_raw', 'full_search_runs', ['full_search_run_id'], ['id'])
    op.alter_column('search_results_raw', 'query_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('search_queries_study_id_fkey'), 'search_queries', type_='foreignkey')
    op.create_foreign_key(op.f('search_queries_study_id_fkey'), 'search_queries', 'studies', ['study_id'], ['id'])
    op.drop_constraint(op.f('screening_decisions_study_id_fkey'), 'screening_decisions', type_='foreignkey')
    op.drop_constraint(op.f('screening_decisions_video_id_fkey'), 'screening_decisions', type_='foreignkey')
    op.drop_constraint(op.f('screening_decisions_reviewer_id_fkey'), 'screening_decisions', type_='foreignkey')
    op.create_foreign_key(op.f('screening_decisions_study_id_fkey'), 'screening_decisions', 'studies', ['study_id'], ['id'])
    op.create_foreign_key(op.f('screening_decisions_video_id_fkey'), 'screening_decisions', 'videos', ['video_id'], ['id'])
    op.create_foreign_key(op.f('screening_decisions_reviewer_id_fkey'), 'screening_decisions', 'reviewers', ['reviewer_id'], ['id'])
    op.drop_constraint(op.f('presentation_codes_video_coding_id_fkey'), 'presentation_codes', type_='foreignkey')
    op.create_foreign_key(op.f('presentation_codes_video_coding_id_fkey'), 'presentation_codes', 'video_coding', ['video_coding_id'], ['id'])
    op.drop_constraint(op.f('pilot_search_runs_study_id_fkey'), 'pilot_search_runs', type_='foreignkey')
    op.drop_constraint(op.f('pilot_search_runs_reviewer_id_fkey'), 'pilot_search_runs', type_='foreignkey')
    op.create_foreign_key(op.f('pilot_search_runs_study_id_fkey'), 'pilot_search_runs', 'studies', ['study_id'], ['id'])
    op.create_foreign_key(op.f('pilot_search_runs_reviewer_id_fkey'), 'pilot_search_runs', 'reviewers', ['reviewer_id'], ['id'])
    op.drop_constraint(op.f('pilot_search_results_pilot_search_run_id_fkey'), 'pilot_search_results', type_='foreignkey')
    op.drop_constraint(op.f('pilot_search_results_query_id_fkey'), 'pilot_search_results', type_='foreignkey')
    op.drop_constraint(op.f('pilot_search_results_reviewer_id_fkey'), 'pilot_search_results', type_='foreignkey')
    op.create_foreign_key(op.f('pilot_search_results_pilot_search_run_id_fkey'), 'pilot_search_results', 'pilot_search_runs', ['pilot_search_run_id'], ['id'])
    op.create_foreign_key(op.f('pilot_search_results_query_id_fkey'), 'pilot_search_results', 'search_queries', ['query_id'], ['id'])
    op.create_foreign_key(op.f('pilot_search_results_reviewer_id_fkey'), 'pilot_search_results', 'reviewers', ['reviewer_id'], ['id'])
    op.alter_column('pilot_search_results', 'query_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('older_adult_need_codes_video_coding_id_fkey'), 'older_adult_need_codes', type_='foreignkey')
    op.create_foreign_key(op.f('older_adult_need_codes_video_coding_id_fkey'), 'older_adult_need_codes', 'video_coding', ['video_coding_id'], ['id'])
    op.drop_constraint(op.f('information_domain_codes_video_coding_id_fkey'), 'information_domain_codes', type_='foreignkey')
    op.create_foreign_key(op.f('information_domain_codes_video_coding_id_fkey'), 'information_domain_codes', 'video_coding', ['video_coding_id'], ['id'])
    op.drop_constraint(op.f('full_search_runs_approval_id_fkey'), 'full_search_runs', type_='foreignkey')
    op.drop_constraint(op.f('full_search_runs_study_id_fkey'), 'full_search_runs', type_='foreignkey')
    op.create_foreign_key(op.f('full_search_runs_approval_id_fkey'), 'full_search_runs', 'search_strategy_approvals', ['approval_id'], ['id'])
    op.create_foreign_key(op.f('full_search_runs_study_id_fkey'), 'full_search_runs', 'studies', ['study_id'], ['id'])
    op.drop_constraint(op.f('double_coding_samples_video_id_fkey'), 'double_coding_samples', type_='foreignkey')
    op.drop_constraint(op.f('double_coding_samples_study_id_fkey'), 'double_coding_samples', type_='foreignkey')
    op.create_foreign_key(op.f('double_coding_samples_video_id_fkey'), 'double_coding_samples', 'videos', ['video_id'], ['id'])
    op.create_foreign_key(op.f('double_coding_samples_study_id_fkey'), 'double_coding_samples', 'studies', ['study_id'], ['id'])
    op.drop_constraint(op.f('audit_log_study_id_fkey'), 'audit_log', type_='foreignkey')
    op.drop_constraint(op.f('audit_log_reviewer_id_fkey'), 'audit_log', type_='foreignkey')
    op.create_foreign_key(op.f('audit_log_study_id_fkey'), 'audit_log', 'studies', ['study_id'], ['id'])
    op.create_foreign_key(op.f('audit_log_reviewer_id_fkey'), 'audit_log', 'reviewers', ['reviewer_id'], ['id'])
    op.drop_constraint(op.f('accuracy_review_status_study_id_fkey'), 'accuracy_review_status', type_='foreignkey')
    op.drop_constraint(op.f('accuracy_review_status_video_id_fkey'), 'accuracy_review_status', type_='foreignkey')
    op.drop_constraint(op.f('accuracy_review_status_reviewer_id_fkey'), 'accuracy_review_status', type_='foreignkey')
    op.create_foreign_key(op.f('accuracy_review_status_study_id_fkey'), 'accuracy_review_status', 'studies', ['study_id'], ['id'])
    op.create_foreign_key(op.f('accuracy_review_status_video_id_fkey'), 'accuracy_review_status', 'videos', ['video_id'], ['id'])
    op.create_foreign_key(op.f('accuracy_review_status_reviewer_id_fkey'), 'accuracy_review_status', 'reviewers', ['reviewer_id'], ['id'])
    op.drop_constraint(op.f('accuracy_claims_study_id_fkey'), 'accuracy_claims', type_='foreignkey')
    op.drop_constraint(op.f('accuracy_claims_video_id_fkey'), 'accuracy_claims', type_='foreignkey')
    op.drop_constraint(op.f('accuracy_claims_reviewer_id_fkey'), 'accuracy_claims', type_='foreignkey')
    op.create_foreign_key(op.f('accuracy_claims_study_id_fkey'), 'accuracy_claims', 'studies', ['study_id'], ['id'])
    op.create_foreign_key(op.f('accuracy_claims_video_id_fkey'), 'accuracy_claims', 'videos', ['video_id'], ['id'])
    op.create_foreign_key(op.f('accuracy_claims_reviewer_id_fkey'), 'accuracy_claims', 'reviewers', ['reviewer_id'], ['id'])
    # ### end Alembic commands ###
